- Makefile
- README.md
- apis/druid/v1alpha1/druid_types.go
- apis/druid/v1alpha1/zz_generated.deepcopy.go
- chart/templates/crds/druid.apache.org_druids.yaml
- controllers/druid/handler.go
- controllers/druid/handler_test.go
- controllers/druid/testdata/broker-pod-disruption-budget.yaml
- deploy/crds/druid.apache.org_druids.yaml
Fixes #5
This PR moves `policy/v1beta1` to `policy/v1` for the PodDisruptionBudget.  `policy/v1beta1` was deprecated in K8s 1.21 and removed in 1.25.  It should be noted that this PR will make K8s <1.21 unsupported.
This PR has:
<hr>
* `PodDisruptionBudget`
> feat: Move policy/v1beta1 to policy/v1 for K8s 1.25+ compatability

- apis/druid/v1alpha1/druid_types.go
- chart/templates/crds/druid.apache.org_druids.yaml
- controllers/druid/handler.go
- controllers/druid/testdata/broker-deployment.yaml
- deploy/crds/druid.apache.org_druids.yaml
Fixes #XXXX.
Druid operator set deployment rollingUpdateStrategy to `maxSurge: 25` and `maxUnavailable: 25`
I think the default values should match the default value of the rollingUpdateStrategy (25% for both fields)  
<hr>
This PR has:
<hr>
* `apis/druid/v1alpha1/druid_types.go`
> fix: set maxSurge and maxUnavailable to 25% by default for deployment

- README.md
Fixes #XXXX.
I 'm trying to improve the documentation.
It can be nice for users to have the Kubernetes compatibility and 2 or 3 version of the operator on the readme
<hr>
This PR has:
<hr>
* `README.md`
> chore(docs): add kubernetes compatibility matrix

- docs/README.md
- docs/dev_doc.md
- docs/druid_cr.md
- Update druid_cr.md and add rollingDeploy
- fix typo
<hr>
This PR has:
<hr>
* `MyFoo`
* `OurBar`
* `TheirBaz`
> chore: add docs on druid_cr.md and fix typos

- apis/druid/v1alpha1/druid_types.go
- chart/templates/crds/druid.apache.org_druids.yaml
- controllers/druid/handler.go
- deploy/crds/druid.apache.org_druids.yaml
Fixes #25 
Kubebuilder supports object validation markers. Instead of validating the object inside the reconcile function (in the verifyDruidSpec function, we should let Kubebuilder do it.
For every required field we're adding the // +required marker.  
For example, nodeType that now looks like this:  
```
// Druid node type
// +required
// +kubebuilder:validation:Enum:=historical;overlord;middleManager;indexer;broker;coordinator;router
NodeType string `json:"nodeType"`
```
will return:
`The Druid "tiny-cluster" is invalid: spec.nodes.brokers.nodeType: Required value` If not specified.  
`The Druid "tiny-cluster" is invalid: spec.nodes.brokers.nodeType: Unsupported value: "brokerr": supported values: "historical", "overlord", "middleManager", "indexer", "broker", "coordinator", "router"` …
> added validations with kubebuilder's markers

- controllers/druid/druid_controller.go
- controllers/druid/handler.go
Fixes #43 
Instead of using `context.TODO()` which is used for development, we will pass the Reconcile function context is describe in [Kubebuilder's documentation](https://book.kubebuilder.io/cronjob-tutorial/controller-overview.html#:~:text=The%20context%20is%20used%20to%20allow%20cancelation%20of%20requests%2C%20and%20potentially%20things%20like%20tracing.%20It%E2%80%99s%20the%20first%20argument%20to%20all%20client%20methods.%20The%20Background%20context%20is%20just%20a%20basic%20context%20without%20any%20extra%20data%20or%20timing%20restrictions.)
<hr>
This PR has:
<hr>
* `controllers/druid/druid_controller.go`
> Pass context from Reconcile function to inside functions

- README.md
linked to #48 
Update compatibility matrix as HPA/v2beta2 is not present anymore in 1.26
> fix: kubernetes compatibility matrix

- apis/druid/v1alpha1/druid_types.go
- chart/templates/crds/druid.apache.org_druids.yaml
- config/crd/bases/druid.apache.org_druids.yaml
- config/druid.apache.org_druids.yaml
- controllers/druid/druid_controller.go
- controllers/druid/druid_controller_test.go
- controllers/druid/handler.go
- controllers/druid/util_test.go
- controllers/druid/zookeeper_dep_mgmt_test.go
- e2e/configs/druid-cr.yaml
Fixes #58 .
<hr>
This PR has:
<hr>
* `handler.go`
* `types.gp`
* `chart/`
> init container support

- docs/examples.md
- docs/features.md
Fixes #74 
In addition to the operator's example usage. This example includes how to configure the metadata storage's password in a secure way.
Also fixing the API version of the supported hpa in another doc.
<hr>
This PR has:
<hr>
* `examples.md`
* `features.md`
> secure metadata storage example

- controllers/druid/handler.go
- controllers/druid/util.go
Fixes #32 
Possibly a race condition is causing removal of PVC in use.
The solution in the PR: Added two labels `toBeDeleted` and `deletionTimestamp` to mark the pvc for deletion. Do not delete the pvc right away, wait for 60s to delete it and avoid the race condition.
<hr>
This PR has:
<hr>
* `controllers/druid/util.go`
> Delay removal of orphanPVC to avoid the removal of PVC in use

- apis/druid/v1alpha1/druid_types.go
- chart/templates/crds/druid.apache.org_druids.yaml
- config/crd/bases/druid.apache.org_druids.yaml
Fixes #81 
Druid requires a [rolling update](https://druid.apache.org/docs/latest/operations/rolling-updates.html) in order to apply changes with no downtime. The operator supports it with the `rollingUpdate` field.  
Currently, this behavior is disabled by default for no reason.
This PR changes Druid's API `rollingUpdate` field to be `true` by default. This is done by using a Kubebuilder marker.
<hr>
This PR has:
<hr>
* `apis/druid/v1alpha1/druid_types.go`
> refactor(api): changing rollingUpdate default to true

- controllers/druid/handler.go
- controllers/druid/testdata/broker-deployment.yaml
- controllers/druid/testdata/broker-statefulset-sidecar.yaml
- controllers/druid/testdata/broker-statefulset.yaml
- docs/features.md
Fixes #55 
Add function to setup default probe properly for each node types 
<hr>
This PR has:
<hr>
* `MyFoo`
* `OurBar`
* `TheirBaz`
> feat: set default probe for each druid components

- chart/Chart.yaml
- chart/templates/deployment.yaml
- chart/values.yaml
Allow the configuration of the Containerimage Repository of the kubebuilder/kube-rbac-proxy in case of usage in private kubernetes clusters
<hr>
This PR has:
<hr>
* `chart/Chart.yaml`
* `chart/templates/deployment.yaml`
* `chart/values.yaml`
> Allow configuration of kubebuilder/kube-rbac-proxy image

- apis/druid/v1alpha1/druid_types.go
- chart/templates/crds/druid.apache.org_druids.yaml
- config/crd/bases/druid.apache.org_druids.yaml
- controllers/druid/handler.go
- controllers/druid/handler_test.go
- controllers/druid/testdata/broker-statefulset-noprobe.yaml
- controllers/druid/testdata/druid-smoke-test-cluster.yaml
- controllers/druid/testdata/druid-test-cr-noprobe.yaml
- controllers/druid/testdata/druid-test-cr.yaml
- docs/api_specifications/druid.md
- docs/features.md
Fixes #97 
1. change historical readiness path to `/druid/historical/v1/readiness`  
Both path has similar purpose. https://druid.apache.org/docs/latest/operations/api-reference/#historical
```
Similar to /druid/historical/v1/loadstatus, but instead of returning JSON with a flag, responses 200 OK if segments in the local cache have been loaded, and 503 SERVICE UNAVAILABLE, if they haven't.
```
2. add defaultProbes bool in druid spec to true by default 
3. update docs and document the issue with middle manager less until we add test case and a fix
<hr>
This PR has:
<hr>
* `docs/features.md`
*  `chart/templates/crds/druid.apache.org_druids.yaml`
* `config/crd/bases/druid.apache.org_druids.yaml`
> fix: readiness probe on historical

- apis/druid/v1alpha1/druid_types.go
- chart/templates/crds/druid.apache.org_druids.yaml
- config/crd/bases/druid.apache.org_druids.yaml
- controllers/druid/handler.go
- controllers/druid/testdata/broker-deployment.yaml
- controllers/druid/testdata/broker-statefulset.yaml
- controllers/druid/testdata/druid-test-cr-noprobe.yaml
- controllers/druid/testdata/druid-test-cr-sidecar.yaml
- controllers/druid/testdata/druid-test-cr.yaml
- docs/api_specifications/druid.md
- e2e/configs/druid-cr.yaml
Fixes ##101
add PriorityClassName to nodeSpec and druidSpec
<hr>
This PR has:
<hr>
* `apis/druid/v1alpha1/druid_types.go`
* `chart/templates/crds/druid.apache.org_druids.yaml`
> feat: add possibility to configure PriorityClassName

- controllers/druid/handler.go
_Note: I am facing this issue with the `v1.0.0` version of the operator on my `< 1.25` K8s cluster. I think the same issue exists with later versions of the operator. So this change is off of the main branch._
Druid cluster has statefulsets with OrderedReady and  we observed that the operator panics and goes into an irrecoverable state with an index-out-of-bounds exception when a pod is in the `Pending` state without creating any containers.
In my case it occurred when:
1. the operator incorrectly deleted the PVC before it could be mounted to the pod and the pod remained in `Pending` state (this is fixed in later versions with https://github.com/datainfrahq/druid-operator/pull/67)
2. Kubernetes cluster didn't have the requested resources and the pod was in the `Pending` state
in both …
> Fix operator panic when checking for pod crashloop status

- e2e/configs/druid-mmless.yaml
- examples/tiny-cluster-mmless.yaml
Fixes #XXXX.
<hr>
This PR has:
<hr>
* `MyFoo`
* `OurBar`
* `TheirBaz`
> MM less Druid Example

- controllers/druid/handler.go
- controllers/druid/testdata/volume-expansion.yaml
- controllers/druid/volume_expansion.go
- controllers/druid/volume_expansion_test.go
Fixes #1 
This PR fixes the issue where the operator gets a nil pointer exception while trying to reach the storage class name of a storage class name template when it is not specified.
Important:  
`StorageClassName` is generally not a required field (https://github.com/kubernetes/kubernetes/blob/0cabb55f7c05eb269ae6f7292271833f095657ec/pkg/apis/core/types.go#L461).  
If a storage class is not provided, Kubernetes checks the default StorageClass (https://kubernetes.io/docs/concepts/storage/storage-classes/#default-storageclass).  
This is tricky because there could be multiple storage classes and very dangerous to Druid (https://github.com/kubernetes/kubernetes/blob/0cabb55f7c05eb269ae6f7292271833f095657ec/test/e2e/framework/pv/pv.go#L822).  
Therefore, we will require users to specify a …
> fix(nil pointer): storage class reference

- apis/druid/v1alpha1/druid_types.go
- apis/druid/v1alpha1/zz_generated.deepcopy.go
- chart/templates/crds/druid.apache.org_druids.yaml
- config/crd/bases/druid.apache.org_druids.yaml
- config/druid.apache.org_druids.yaml
- controllers/druid/handler.go
- docs/api_specifications/druid.md
- e2e/configs/druid-mmless.yaml
- examples/tiny-cluster-mmless.yaml
Fixes #119 
Made the spelling of startup probe config consistent for nodeSpec and druidSpec. 
This PR has:
<hr>
* `apis/druid/v1alpha1/druid_types.go`
* `apis/druid/v1alpha1/zz_generated.deepcopy.go`
* `chart/templates/crds/druid.apache.org_druids.yaml`
* `config/crd/bases/druid.apache.org_druids.yaml`
* `config/druid.apache.org_druids.yaml`
* `docs/api_specifications/druid.md`
* `e2e/configs/druid-mmless.yaml`
* `examples/tiny-cluster-mmless.yaml`
> fix: made the startup probe consistent for nodespec and druidspec

- controllers/druid/druid_controller.go
- controllers/druid/finalizers.go
- controllers/druid/finalizers_test.go
- controllers/druid/handler.go
- controllers/druid/interface.go
- controllers/druid/suite_test.go
- controllers/druid/testdata/finalizers.yaml
- controllers/druid/types.go
Code refactoring to the finalizers' logic. Added also tests.  
I didn't refactor the entire code since its complicated to do all at once.
<hr>
This PR has:
<hr>
* `controllers/druid/finalizers.go`
* `controllers/druid/finalizers_test.go`
* `controllers/druid/suite_test.go`
> (finalizers): refactor

- e2e/e2e.sh
- main.go
Fixes #XXXX.
@itamar-marom can you help in reviewing this one. 
```
adheipsingh@Adheips-Air ~ % k logs -f cluster-druid-operator-6c7b966548-rj58x  -n druid-operator-system -c manager
2024-02-09T15:24:02Z	ERROR	setup	unable to start manager	{"error": "must specify more than one namespace to use multi-namespace cache"}
main.main
/workspace/main.go:93
runtime.main
/usr/local/go/src/runtime/proc.go:250
```
- This issue arises when we have both ```Namespace``` and ```NewCache``` enabled for a single namespace to watch. 
- This PR add a check in watchNamespaceCache() to built cache only if multiple namespace are found, so runtime can default to watch namespace for single and NO namespace specified to watch. 
<hr>
This PR has:
<hr>
* `MyFoo`
* `OurBar`
* `TheirBaz`
> fix multinamespace cache isue

- controllers/druid/handler.go
In the `checkCrashStatus` we are listing all the pods in the namespace for all of the druid components which does not seems right. Since we are in the loop executing the deployment operations for a single nodeSpec we should be only listing the pods which belong to that particular NodeType
<hr>
This PR has:
<hr>
> List only pod specific to a nodespec while checking the crash status

- Makefile
Attempted to follow the instructions in the _**Running Operator Locally**_ section of the developer documentation. When I attempted to run `make install` I encountered a nil pointer dereference error. (See stack trace below.)
Looking into the stack trace I realised the error originated from the `controller-gen` command from the **controller-tools** package. Looking into said package, I realised that the latest released version is `v.0.14.0`. The version referenced in `Makefile` were `v0.11.2`. I tried to change the referenced version to the latest version and it solved the nil pointer dereferenced issue and I could continue following the developer documentation.
<hr>
This PR has:
<hr>
* `Makefile`
> Bump controller-tools version

- Makefile
- chart/templates/rbac_manager.yaml
- controllers/ingestion/reconciler.go
- e2e/Dockerfile-testpod
- e2e/configs/druid-ingestion-cr.yaml
- e2e/druid-ingestion-test.sh
- e2e/e2e.sh
- e2e/monitor-task.sh
- e2e/wikipedia-test.sh
Fixes [#137.](https://github.com/datainfrahq/druid-operator/issues/137)
This adds a step which creates a Druid Ingestion controller and verifies its output in e2e tests. 
A few other fixes:
- Added missing DruidIngestion access to the rbac policies in the chart
- un-commented a line in `controllers/ingestion/reconciler.go` - was this meant to be commented out?
> Utilize the DruidIngestion controller in e2e tests

- docs/getting_started.md
- examples/aws/eks.yaml
Fixes #147 .
`examples/aws/eks.yaml` was missing volumeClaim and volume causing the deployment to fail. I added them. Additionally, I improved the "getting_started" documentation, pointing out the minio dependency for most of the examples and referencing the makefile for bootstrapping minio.
<hr>
This PR has:
<hr>
* `examples/aws/eks.yaml`
* `docs/getting_started.md`
> fix(eks deployment): Add expected volumeClaim to eks.yaml 

- apis/druid/v1alpha1/druid_types.go
- apis/druid/v1alpha1/zz_generated.deepcopy.go
- chart/templates/crds/druid.apache.org_druids.yaml
- config/crd/bases/druid.apache.org_druids.yaml
- controllers/druid/handler.go
- controllers/druid/testdata/broker-deployment.yaml
- controllers/druid/testdata/broker-statefulset.yaml
- controllers/druid/testdata/druid-test-cr.yaml
- docs/api_specifications/druid.md
- e2e/configs/druid-cr.yaml
Fixes https://github.com/datainfrahq/druid-operator/issues/142
Adding a `ReplicationControllerAnnotations` field to the DruidNodeSpec schema. This allows users to specify annotations to be applied to the StatefulSet / Deployment object. 
I'm not 100% sure of the naming - what do you think? I didn't want to call it `StatefulSetAnnotations` since the user can opt for a deployment instead.
Also regenerated the API docs, which led to a huge diff as it appears they weren't regenerated after https://github.com/datainfrahq/druid-operator/pull/53 (hence the huge diff)
This PR has:
I haven't tested this on a real kube cluster, but all of the e2e tests run. Is that sufficient for an overall minor/straightforward change?
> Add support for annotations on Deployment/StatefulSet resources in DruidNodeSpec

- controllers/druid/volume_expansion.go
Fixes #106 .
Multi tier historicals:
- Cold
- Hot
as shown in the screenshot below can have different storage sizes for the PVC.
<hr>
This PR has:
<hr>
> Add support for multi tier nodes with different PVC sizes (#106)

- controllers/druid/handler.go
Fixes #183 
The operator does not add node spec's podLabels to the statefulsets unless a user also defines podLabels for the cluster spec.
This change will always add both cluster and node spec podLabels as long as they are defined. If same labels are defined for both cluster spec and pod spec then it'll prefer node spec values over cluster spec.
<hr>
This PR has:
<hr>
> Fix node spec podLabels bug

- docs/features.md
The documentation for the "Default Yet Configurable" `startUpProbe` contains a small typo where the `u` in `startUp` is not capitalized. This can cause some confusion when trying to incorporate this example config into a Druid configuration.
<hr>
This PR has:
<hr>
* `docs/features.md`
> Fix typo in probe definition

- chart/templates/rbac_manager.yaml
- chart/templates/rbac_metrics.yaml
- chart/templates/rbac_proxy.yaml
- chart/values.yaml
Related to #170 and #162 
When destroying and re-creating the operator (for example when moving to another namespace) we want to keep CRDs and ClusterRoles around. This PR adds an option `createClusterRoles` to the helm chart which can be used to re-create the operator without re-creating the ClusterRoles, which would currently fail.
The default value is true and thus default behavior of the chart will not change.
This PR has:
> feat(chart): option to not create clusterRoles;

- chart/templates/rbac_manager.yaml
- controllers/ingestion/reconciler.go
- e2e/configs/kafka-ingestion.yaml
- e2e/configs/minio-tenant-override.yaml
- e2e/e2e.sh
- examples/kafka-ingestion.yaml
- Implemented functionality to submit Kafka ingestion specs
- Fixed integration tests
- Updated RBAC rules to include Secret verbs for authenticated API usage
Fixes #135.
Adds support for Kafka ingestion
<hr>
This PR has:
<hr>
* `controllers/ingestion/reconciler.go`
> Add Kafka Ingestion Spec Submission

- chart/templates/deployment.yaml
- chart/values.yaml
Fixes #190
<hr>
Adds podLabels to druid-operator deployment to allow adding custom labels to the druid operator node.
This PR has:
<hr>
* changed deployment.yaml
* changed values.yaml
> add podLabels to druid-operator deployment

- docs/README.md
This shall help users to adapt to the setup and config of Druid on Kubernetes using your operator. Due to the current lack of examples I've posted this on the druid slack channel and @AdheipSingh thought it would be of value here.
In Context of the fahrbar20 project from iunera for the German Ministry of Digital and Transport, we decided to publish all our code and findings. Furthermore we love Druid and want to help with the adaption of users. 
<hr>
This PR has:
<hr>
* `docs/README.md`
> Add Production-ready druid cluster spec

- pkg/druidapi/druidapi.go
Fixes #213.
GetRouterSvcUrl in druidapi.go hard-codes cluster.local as a domain suffix.  This breaks DruidIngestion for Kubernetes clusters that use a custom cluster name.  But, given that GetRouterSvcUrl will be called within the same namespace as the router service, there is no need to use a fully qualified name.  By using the relative name, we avoid needing to look up what domain suffix to use.
This patch removes `svc.cluster.local` from the URL of the Druid router service returned by GetRouterSvcUrl.
If this patch is rejected for not using the fqdn, then we need to dynamically look up the current cluster domain rather than assume it is `cluster.local`.
<hr>
This PR has:
<hr>
* `pkg/druidapi/druidapi.go`
> Stop using cluster domain suffix for DruidIngestion

- chart/crds/druid.apache.org_druidingestions.yaml
- chart/crds/druid.apache.org_druids.yaml
- config/crd/bases/druid.apache.org_druidingestions.yaml
- config/crd/bases/druid.apache.org_druids.yaml
- docs/api_specifications/druid.md
- go.mod
- go.sum
- pkg/druidapi/druidapi.go
- pkg/druidapi/druidapi_test.go
I have druid cluster managed with this operator and encountered limitation when trying to use existing secrets that have different key names for authentication credentials. The operator was hardcoded to look for specific keys `OperatorUserName` and `OperatorPassword` in kubernetes secrets.
The possible solutions were:
1. Create new secrets with expected key names (e.g. external-secret operator) - but this creates duplication and maintenance overhead
2. Modify operator to accept custom key names - chosen solution as it provides flexibility without breaking existing functionality
This PR adds optional `usernameKey` and `passwordKey` fields to Auth configuration.
<hr>
This PR has:
<hr>
* `pkg/druidapi/druidapi.go` - Updated Auth struct and GetAuthCreds function to support custom keys
* …
> feat: Add support for custom username and password keys in auth.

- examples/tiny-cluster-mmless.yaml
Gets the pods to contact to each other locally. Without these changes, the pods were using the entire pod name to be able to connect with each other.
However, in k8s, the dns records for pod names doesn't exist, however they exist for specific nodes. Kindly see the example
```
bash-5.1# nslookup druid-tiny-cluster-coordinators-56d5865467-2hmqc
Server:         10.96.0.10
Address:        10.96.0.10:53
** server can't find druid-tiny-cluster-coordinators-56d5865467-2hmqc.cluster.local: NXDOMAIN
** server can't find druid-tiny-cluster-coordinators-56d5865467-2hmqc.cluster.local: NXDOMAIN
** server can't find druid-tiny-cluster-coordinators-56d5865467-2hmqc.druid.svc.cluster.local: NXDOMAIN
** server can't find druid-tiny-cluster-coordinators-56d5865467-2hmqc.svc.cluster.local: NXDOMAIN
** …
```
> Make local k8s setup work for mmless configuration
